-- ═══════════════════════════════════════════════
-- ITADOG — Seed Data (clientes e produtos iniciais)
-- Execute APÓS o schema.sql
-- ═══════════════════════════════════════════════

-- ─── CLIENTES ───────────────────────────────────
INSERT INTO clients (name, city, freq, day) VALUES
('A CASA DO PET BAL. CAMBORIÚ',     'Balneário Camboriú', 15, 3),
('AGROPECUARIA AGRO RURAL (CAMBORIU)','Camboriú',         15, 3),
('AGROPECUARIA AGROJEPE',            'Itajaí',            15, 1),
('AGROPECUARIA AMARAL (BARRA VELHA)','Barra Velha',       15, 5),
('AGROPECUARIA AMARAL (PENHA)',       'Penha',             15, 5),
('AGROPECUARIA ARARIPE',              'Itajaí',            15, 1),
('AGROPECUARIA ARRAIAL (PICARRAS)',   'Piçarras',          15, 4),
('AGROPECUARIA BOA SORTE',            'Itajaí',            15, 2),
('AGROPECUARIA BRASIL (NAVEGANTES)', 'Navegantes',        15, 4),
('AGROPECUARIA DA FAMILIA',           'Itajaí',            15, 1),
('AGROPECUARIA DO CAMPO',             'Barra Velha',       15, 5),
('AGROPECUARIA FENIX',                'Balneário Camboriú',15, 3),
('AGROPECUARIA IMPERIAL',             'Itajaí',            15, 2),
('AGROPECUARIA IMPACTO',              'Navegantes',        15, 4),
('AGROPECUARIA IZIDORO',              'Balneário Camboriú',15, 3),
('AGROPECUARIA LAGOINHA',             'Navegantes',        15, 4),
('AGROPECUARIA MORRETES',             'Navegantes',        15, 4),
('AGROPECUARIA NAGIB (PICARRAS)',     'Piçarras',          15, 4),
('AGROPECUARIA PENHA',                'Penha',             15, 5),
('AGROPECUARIA PICARRAS',             'Piçarras',          15, 4),
('AGROPECUARIA PLANETA PET',          'Itajaí',            15, 1),
('AGROPECUARIA REAL',                  'Balneário Camboriú',15, 3),
('AGROPECUARIA ROMAX',                 'Itajaí',            15, 2),
('AGROPECUARIA SAO PEDRO',             'Navegantes',        15, 4),
('AGROPECUARIA VIEIRA',                'Itajaí',            15, 1),
('AGROPECUARIA VOLTA REDONDA',         'Itajaí',            15, 2),
('CASA DOS ANIMAIS',                   'Balneário Camboriú',15, 3),
('EMPORIO DOS ANIMAIS',                'Balneário Camboriú',15, 3),
('FAZENDA PET SHOP',                   'Itajaí',            15, 1),
('LAGOINHA PET SHOP',                  'Navegantes',        15, 4),
('MIAU E LATIDO PET',                  'Penha',             15, 5),
('MUNDO ANIMAL',                       'Itajaí',            15, 2),
('PET BELEM',                          'Balneário Camboriú',15, 3),
('PET CENTER BIGUAÇU',                 'Biguaçu',           15, 2),
('PET MANIA',                          'Itajaí',            15, 1),
('PET SHOP ANIMAL',                    'Navegantes',        15, 4),
('PET SHOP DO TIÃO',                   'Itajaí',            15, 2),
('PET SHOP MUNDO PET',                 'Balneário Camboriú',15, 3),
('PET SHOP PLANALTO',                  'Itajaí',            15, 1),
('PET SHOP RAIMUNDO',                  'Piçarras',          15, 4),
('PLANETA ANIMAL',                     'Navegantes',        15, 4),
('SUPER PET',                          'Balneário Camboriú',15, 3),
('VET ANIMALS',                        'Barra Velha',       15, 5),
('VIDA ANIMAL',                        'Itajaí',            15, 1),
('ZOONOSE PET',                        'Balneário Camboriú',15, 3)
ON CONFLICT DO NOTHING;

-- ─── PRODUTOS ───────────────────────────────────
INSERT INTO products (id, code, description, cost, price, category, colors) VALUES
('OO1','OO1','PEITORAL DE NY TUBOLAR FITA 15 Nº 00',4.95,9.9,'Peitoral',ARRAY['azul','rosa','preto','verm']),
('OO2','OO2','PEITORAL DE NY TUBOLAR FITA 15 Nº 0', 4.95,9.6,'Peitoral',ARRAY['azul','rosa','preto','verm']),
('OO3','OO3','PEITORAL DE NY TUBOLAR FITA 15 Nº 1', 4.95,10.9,'Peitoral',ARRAY['azul','rosa','preto','verm']),
('OO4','OO4','PEITORAL DE NY TUBOLAR FITA 15 Nº 2', 5.65,11.9,'Peitoral',ARRAY['azul','rosa','preto','verm']),
('OO5','OO5','PEITORAL DE NY TUBOLAR FITA 15 Nº 3', 5.65,13.5,'Peitoral',ARRAY['azul','rosa','preto','verm']),
('OO6','OO6','PEITORAL DE NYLON FITA 20 NR 3',      6.85,12.9,'Peitoral',ARRAY['azul','rosa','preto','verm']),
('OO7','OO7','PEITORAL DE NYLON FITA 20 NR 4',      6.85,12.9,'Peitoral',ARRAY['azul','rosa','preto','verm']),
('OO8','OO8','PEITORAL DE NYLON FITA 20 NR 5',      6.85,13.5,'Peitoral',ARRAY['azul','rosa','preto','verm']),
('O19','O19','PEITORAL POLIESTER EM X FITA 15 Nº M',7.85,13.6,'Peitoral',ARRAY['azul','rosa','preto','verm']),
('O20','O20','PEITORAL POLIESTER EM X FITA 15 Nº G',7.85,14.9,'Peitoral',ARRAY['azul','rosa','preto','verm']),
('O22','O22','PEITORAL POLIESTER EM X FITA 20 Nº M',9.7,16.9,'Peitoral',ARRAY['azul','rosa','preto','verm']),
('O23','O23','PEITORAL POLIESTER EM X FITA 20 Nº G',9.7,18.9,'Peitoral',ARRAY['azul','rosa','preto','verm']),
('O59','O59','PEITORAL NYLON NEOPREME Nº M',         18.84,41.9,'Peitoral',ARRAY['azul','rosa','preto','verm']),
('O60','O60','PEITORAL NYLON NEOPREME Nº G',         18.84,42.9,'Peitoral',ARRAY['azul','rosa','preto','verm']),
('O53','O53','GUIA DE NYLON TUBOLAR FITA 15 C/ 1 MT',2.4,4.5,'Guia',ARRAY['azul','rosa']),
('O54','O54','GUIA DE POLIESTER FITA 15 C/ 1 MT',    2.4,6.5,'Guia',ARRAY['azul','rosa']),
('O55','O55','GUIA DE POLIESTER DUPLA C/ 60 CM',     2.4,12.5,'Guia',ARRAY['azul','rosa']),
('O56','O56','GUIA DE POLIESTER DUPLA C/ 1 MT',      2.4,14.5,'Guia',ARRAY['azul','rosa']),
('O58','O58','CINTO SEGURANÇA PET POLIESTER FITA 25',7.2,11.9,'Outros',ARRAY[]::TEXT[]),
('O65','O65','COL. COURO NATURAL Nº2',1.99,2.8,'Coleira',ARRAY['azul','rosa','preto','verm']),
('O66','O66','COL. COURO NATURAL Nº3',3.05,4.35,'Coleira',ARRAY['azul','rosa','preto','verm']),
('O67','O67','COL. COURO NATURAL Nº4',4.2,6.0,'Coleira',ARRAY['azul','rosa','preto','verm']),
('O68','O68','COL. COURO NATURAL Nº5',4.38,6.2,'Coleira',ARRAY['azul','rosa','preto','verm']),
('O69','O69','COL. COURO NATURAL Nº6',5.7,7.6,'Coleira',ARRAY['azul','rosa','preto','verm']),
('O70','O70','COL. COURO NATURAL Nº7',7.99,9.9,'Coleira',ARRAY['azul','rosa','preto','verm']),
('O71','O71','COL. COURO NATURAL Nº8',9.58,12.2,'Coleira',ARRAY['azul','rosa','preto','verm']),
('O72','O72','COL. COURO NATURAL Nº9',13.15,16.9,'Coleira',ARRAY['azul','rosa','preto','verm']),
('O73','O73','COL COUR NATURAL Nº10', 14.65,18.9,'Coleira',ARRAY['azul','rosa','preto','verm']),
('O77','O77','COL. COURO PINTADA Nº4',4.2,6.65,'Coleira',ARRAY['azul','rosa','preto','verm']),
('O79','O79','COL. COURO PINTADA Nº6',5.7,11.0,'Coleira',ARRAY['azul','rosa','preto','verm']),
('O80','O80','COL. COURO PINTADA Nº7',7.99,13.6,'Coleira',ARRAY['azul','rosa','preto','verm']),
('O81','O81','COL. COURO PINTADA Nº8',9.58,14.8,'Coleira',ARRAY['azul','rosa','preto','verm']),
('O82','O82','COL. COURO PINTADA Nº9',13.15,17.9,'Coleira',ARRAY['azul','rosa','preto','verm']),
('O83','O83','COL. COURO PINTADA Nº10',14.65,18.9,'Coleira',ARRAY['azul','rosa','preto','verm']),
('O50','O50','COLEIRA REGUL POLIESTER FITA 15 TAM P',2.5,5.9,'Coleira',ARRAY['azul','rosa','preto','verm']),
('O51','O51','COLEIRA REGUL POLIESTER FITA 20 TAM M',2.9,6.9,'Coleira',ARRAY['azul','rosa','preto','verm']),
('O52','O52','COLEIRA REGUL POLIESTER FITA 25 TAM G',3.5,8.9,'Coleira',ARRAY['azul','rosa','preto','verm']),
('O97','O97','COLEIRA ELAST. PARA GATOS TAM. ÚNICO',2.1,3.8,'Coleira',ARRAY['azul','rosa']),
('O98','O98','PEITORAL POLIESTER GATO TAM ÚNICO',   2.1,12.9,'Peitoral',ARRAY['azul','rosa']),
('106','106','COLEIRA POLIESTER DUPLA NR 3 FITA 20',6.65,6.5,'Coleira',ARRAY['azul','rosa']),
('107','107','COLEIRA POLIESTER DUPLA NR 4 FITA 20',7.65,7.9,'Coleira',ARRAY['azul','rosa']),
('108','108','COLEIRA POLIESTER DUPLA NR 5 FITA 25',8.65,8.5,'Coleira',ARRAY['azul','rosa']),
('109','109','COLEIRA POLIESTER DUPLA NR 6 FITA 25',9.65,9.5,'Coleira',ARRAY['azul','rosa']),
('110','110','COLEIRA POLIESTER DUPLA NR 7 FITA 30',12.9,14.5,'Coleira',ARRAY['azul','rosa']),
('111','111','ALMOFADA COM SILICONE TAM P', 15.7,26.9,'Almofada',ARRAY[]::TEXT[]),
('112','112','ALMOFADA COM SILICONE TAM M', 16.7,29.9,'Almofada',ARRAY[]::TEXT[]),
('113','113','ALMOFADA COM SILICONE TAM G', 17.7,32.9,'Almofada',ARRAY[]::TEXT[]),
('114','114','ALMOFADA COM SILICONE TAM GG',21.2,39.9,'Almofada',ARRAY[]::TEXT[]),
('115','115','ALMOFADA COM SILICONE TAM EG',24.2,46.9,'Almofada',ARRAY[]::TEXT[]),
('116','116','ALMOFADA COM SILICONE TAM EGGG',25.4,53.9,'Almofada',ARRAY[]::TEXT[]),
('117','117','CAMA LEDY P',2.0,32.9,'Cama',ARRAY[]::TEXT[]),
('118','118','CAMA LEDY M',25.4,43.9,'Cama',ARRAY[]::TEXT[]),
('119','119','CAMA LEDY G',25.4,54.9,'Cama',ARRAY[]::TEXT[]),
('120','120','SUETER TAM 00',25.4,6.5,'Suéter',ARRAY[]::TEXT[]),
('121','121','SUETER TAM 0', 25.4,8.25,'Suéter',ARRAY[]::TEXT[]),
('122','122','SUETER TAM 02',25.4,8.5,'Suéter',ARRAY[]::TEXT[]),
('123','123','SUETER TAM 04',25.4,8.9,'Suéter',ARRAY[]::TEXT[]),
('124','124','SUETER TAM 06',25.4,12.0,'Suéter',ARRAY[]::TEXT[]),
('125','125','SUETER TAM 08',25.4,14.2,'Suéter',ARRAY[]::TEXT[]),
('126','126','SUETER TAM 10',25.4,14.5,'Suéter',ARRAY[]::TEXT[]),
('127','127','SUETER TAM 12',25.4,16.9,'Suéter',ARRAY[]::TEXT[]),
('128','128','SUETER TAM 14',25.4,17.5,'Suéter',ARRAY[]::TEXT[])
ON CONFLICT (id) DO NOTHING;
